### ISSUE TITLE
track "Flow" property for Video events

### ISSUE THREAD

**Issue by carter2422** [CGCookie/cgc-segment#45]
We need to know what flow a video is associated with.

@bearded-avenger I believe this is now possible as of last week? Can you point me in the right direction?

**Comment by bearded-avenger** [comment]
https://github.com/CGCookie/cgc-core/blob/release/6.0/public/includes/functions--theme-functions.php#L761

**Comment by carter2422** [comment]
@etcook this will go out Thursday to help you with your engagement reporting.
