### ISSUE TITLE
cgcUserAPI

### ISSUE THREAD

**Issue by etcook** [CGCookie/cgc-segment#47]
Nov 24 19:24:35 cgcookie-five-remote-syslog2-1 hhvm.error.log:  \nFatal error: Class undefined: cgcUserAPI in /home/alpha/deployments/cgcookie.com/releases/20151124215655/web/app/plugins/cgc-segment/cgc-segment.php on line 258

**Comment by carter2422** [comment]
I can't reproduce this now, pretty sure it's no longer an issue.
