### ISSUE TITLE
Track Love Sharing

### ISSUE THREAD

**Issue by bearded-avenger** [CGCookie/cgc-segment#50]
`do_action('cgc_share_love_sent', $sender_id, $recipient_id );`

**Comment by bearded-avenger** [comment]
on lab

**Comment by carter2422** [comment]
:+1:

**Comment by bearded-avenger** [comment]
test sent

**Comment by carter2422** [comment]
Closed via https://github.com/CGCookie/cgc-segment/commit/72796b28dc7120180cabc9d432b846b1e8ea6903
